{% set version = '0.9.5.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringdist
  version: {{ version|replace("-", "_") }}

source:
  fn: stringdist_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/stringdist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stringdist/stringdist_{{ version }}.tar.gz
  sha256: aa8b6e3f25c820512ac224e73bc00728ee9b15136cdaaf71ffe042ded30b573d

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('stringdist')"           # [not win]
    - "\"%R%\" -e \"library('stringdist')\""  # [win]

about:
  home: https://github.com/markvanderloo/stringdist
  license: GPL-3
  summary: Implements an approximate string matching version of R's native 'match' function.
    Can calculate various string distances based on edits (Damerau-Levenshtein, Hamming,
    Levenshtein, optimal sting alignment), qgrams (q- gram, cosine, jaccard distance)
    or heuristic metrics (Jaro, Jaro-Winkler). An implementation of soundex is provided
    as well. Distances can be computed between character vectors while taking proper
    care of encoding or between integer vectors representing generic sequences. This
    package is built for speed and runs in parallel by using 'openMP'. An API for C
    or C++ is exposed as well.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - croth1
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
