travis:
  secure:
    BINSTAR_TOKEN: KkNUEguGI/o1nUY/uihEueZ2fSkit/vyjggH6Nsg27WhX2MPOemudqiv+QzTBxbEe3Od4E4iTk3L6vhQ9wBt6kmZtCn/DTnWlLgsAmAOirloFEj0QtEc2U/a52R9PQp6cnKUymKrACt1fcemNJvqb8tGeg9CpkiOS+lnS5rYYREwJYMjLaVpAFP+HYQvgVfq2hGfTs4sQxQhRhEZ0T5PfeFE3XSxQTculFCS+FRArdNfLrNiOYGubITZoLqJRoO2GPNweChj4FfjwNqiUsrrU3SQNvAu2la2HtpoTr+FKfxwfanvbUnUlw160nQJvXfjLattSe4dDWmzdYLbf3pe12oB8uh/T015yyM/4vZdGZ7l2mCahE4z8ZfEckIJJosbSUr0WFcnkZIwXwZ7d2DULy7BKyb4YWK9TdPewmmGIP9iKK94QkGCeYES8SghVWWkYIHjYQtsZJB0LZWxEcTGVqChyUu5/UeCOj7oVVeJya/Mq/Kzy91IQLWNQk1LGfNUb5BOG7bvlw6vYACf/P/mEjoIeiEpfrLSvSUx3pCIj0tejvl1UiRoWe0aIAxCz9iSxJABFQfXhrJlTPZ1HKK55PqN5/1QhM6XIud21vqbeKbJsJ5bIk6WgYX8tlQO717vF2ybybAxH6nJ2GyYijbMTnF0xvrlAs4+qKX0VUnOqFY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
